version: "3.3"
services:
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./server/certbot/conf:/etc/letsencrypt
            - ./server/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
    ## Contenedor de nginx principal para los proyectos combinados
    ppa_nginx:
        container_name: ppa-nginx
        build:
            context: ./
            dockerfile: build/nginx/Dockerfile
        volumes:
            - ./server/nginx.conf:/etc/nginx/nginx.conf
            - ./server/security-headers.conf:/etc/nginx/security-headers.conf
            - ./server/sites/server.conf:/etc/nginx/conf.d/default.conf
            - ./data/login-static:/var/www/html/login_static
            - ./server/certbot/conf:/etc/letsencrypt
            - ./server/certbot/www:/var/www/certbot
        ports:
            - 80:80
            - 443:443
        restart: always
        networks:
            - brief-network

networks:
    brief-network:
        #external: true
